# Generated by Django 5.1.4 on 2025-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSW_ATV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='data publicada')),
            ],
        ),
    ]
