# Generated by Django 5.1.4 on 2025-01-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSW_ATV', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=255, verbose_name='Nome da Categoria')),
                ('cod_categoria', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('cod_fornecedor', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(to='DSW_ATV.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DSW_ATV.fornecedor'),
        ),
    ]
