# Generated by Django 5.1.4 on 2025-01-30 18:31

import DSW_ATV.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSW_ATV', '0004_rename_fornecer_produto_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[DSW_ATV.validators.validate_price]),
        ),
    ]
