# Generated by Django 5.1.4 on 2025-01-30 18:47

import DSW_ATV.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSW_ATV', '0006_alter_produto_qntd_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_produto',
            field=models.CharField(max_length=100, unique=True, validators=[DSW_ATV.validators.validate_code]),
        ),
    ]
