# Generated by Django 5.1.4 on 2025-01-30 18:55

import DSW_ATV.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSW_ATV', '0007_alter_produto_cod_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=255, validators=[DSW_ATV.validators.validate_lenght]),
        ),
    ]
